"""RAG over the document corpus with citations (#25).

Retrieval is a deterministic term-overlap scan over ingested ``Document`` raw
text (no external vector service required) — fully testable. The answer is then
generated by the configured AI provider, grounded *only* in the retrieved
snippets, and every answer ships with its citations so claims trace back to
sources.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.ai.service import ai_service
from app.models.document import Document

_WORD = re.compile(r"[a-z0-9]+")
_STOP = {
    "the", "a", "an", "of", "to", "and", "or", "in", "on", "is", "are", "was",
    "were", "who", "what", "which", "with", "for", "by", "about", "did", "does",
    "do", "how", "when", "where", "that", "this", "from", "has", "have",
}


def _tokens(text: str) -> list[str]:
    return [t for t in _WORD.findall(text.lower()) if t not in _STOP and len(t) > 1]


@dataclass(slots=True)
class Citation:
    document_id: str
    entity_id: str | None
    title: str
    snippet: str
    score: float


# Below this top retrieval score, the corpus does not really address the
# question; answering anyway is how a RAG system hallucinates "grounded" claims.
# We refuse instead. Tuned to admit genuine matches (e.g. 2/3 query-term overlap)
# while rejecting incidental single-term hits.
MIN_GROUNDING_SCORE = 0.15

_REFUSAL = (
    "The corpus does not contain enough relevant evidence to answer this "
    "confidently. Refusing rather than guessing. Add sourced documents and retry."
)


@dataclass(slots=True)
class RagResult:
    answer: str
    provider: str
    citations: list[Citation] = field(default_factory=list)
    # True only when the answer is grounded in retrieved sources above the floor.
    grounded: bool = False


def _snippet(text: str, terms: set[str], width: int = 160) -> str:
    low = text.lower()
    pos = min((low.find(t) for t in terms if low.find(t) >= 0), default=-1)
    if pos < 0:
        return text[:width].strip()
    start = max(0, pos - width // 2)
    return ("…" if start > 0 else "") + text[start:start + width].strip() + "…"


async def retrieve(db: AsyncSession, question: str, *, k: int = 5) -> list[Citation]:
    terms = set(_tokens(question))
    if not terms:
        return []
    docs = list((await db.execute(select(Document))).scalars().all())
    scored: list[tuple[float, Document]] = []
    for doc in docs:
        haystack = set(_tokens(f"{doc.title}\n{doc.raw_text}"))
        overlap = terms & haystack
        if overlap:
            scored.append((len(overlap) / len(terms), doc))
    scored.sort(key=lambda s: s[0], reverse=True)
    return [
        Citation(
            document_id=str(doc.id), entity_id=str(doc.entity_id) if doc.entity_id else None,
            title=doc.title, snippet=_snippet(doc.raw_text or doc.title, terms),
            score=round(score, 4),
        )
        for score, doc in scored[:k]
    ]


async def answer(db: AsyncSession, question: str, *, k: int = 5) -> RagResult:
    citations = await retrieve(db, question, k=k)
    if not citations:
        return RagResult(
            answer="No documents in the corpus match this question.",
            provider=ai_service.provider_name, grounded=False,
        )

    # Refuse-beyond-evidence: if even the best match barely overlaps the question,
    # the corpus does not address it. Return the (weak) citations for transparency
    # but do NOT synthesize an answer — that is exactly where RAG hallucinates.
    if citations[0].score < MIN_GROUNDING_SCORE:
        return RagResult(
            answer=_REFUSAL, provider=ai_service.provider_name,
            citations=citations, grounded=False,
        )

    context = "\n\n".join(
        f"[{i + 1}] {c.title}: {c.snippet}" for i, c in enumerate(citations)
    )
    context += (
        "\n\nAnswer the question using ONLY the numbered sources above, and cite "
        "each claim as [n]. Do not use any outside knowledge. If the sources do "
        "not contain the answer, reply exactly: 'The sources do not answer this.'"
    )
    text = await ai_service.summarize(f"Question: {question}", context)
    return RagResult(
        answer=text, provider=ai_service.provider_name,
        citations=citations, grounded=True,
    )
